import typing as t
from . import compat as compat, misc as misc

def normalize_scheme(scheme: str) -> str: ...
def normalize_authority(
    authority: tuple[str | None, str | None, str | None]
) -> str: ...
def normalize_username(username: str) -> str: ...
def normalize_password(password: str) -> str: ...
def normalize_host(host: str) -> str: ...
def normalize_path(path: str) -> str: ...
@t.overload
def normalize_query(query: str) -> str: ...
@t.overload
def normalize_query(query: None) -> None: ...
@t.overload
def normalize_fragment(fragment: str) -> str: ...
@t.overload
def normalize_fragment(fragment: None) -> None: ...
def normalize_percent_characters(s: str) -> str: ...
def remove_dot_segments(s: str) -> str: ...
@t.overload
def encode_component(uri_component: None, encoding: str) -> None: ...
@t.overload
def encode_component(uri_component: str, encoding: str) -> str: ...
